apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy
on:
  workflow_call:
    inputs:
      artifact-id:
        type: string
        required: true
      artifactVersion:
        type: string
        required: true
      environment:
        type: string
        required: true

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    steps:
      - name: Run deploy
        kind: deploy
        uses: https://github.com/cloudbees-io/cbci-run-job@v2
        with:
          url: ${{ vars.CBCI_URL }}
          username: ${{ secrets.CBCI_USERNAME }}
          token: ${{ secrets.CBCI_TOKEN }}
          job-name: deploy
      - name: Register deployed artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: ${{ inputs.artifact-id }}
          artifactVersion: ${{ inputs.artifactVersion }}
